// Kina studyjne w Polsce — dane zebrane 2026-07-29 (research ze stron kin)
const KINA = [
 {
  "name": "Kino Iskra",
  "city": "Augustów",
  "address": "ul. 3 Maja 38",
  "lat": 53.841983,
  "lng": 22.985366,
  "website": "https://kino-iskra.pl/",
  "repertuarUrl": "https://kino-iskra.pl/cennik/",
  "priceNormal": 22,
  "priceDiscount": 19,
  "priceMin": 15,
  "priceNote": "Tania środa 17 zł; Seanse Seniora i Malucha 15 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Kultura",
  "city": "Bełchatów",
  "address": "Plac Gabriela Narutowicza 1a",
  "lat": 51.3665747,
  "lng": 19.3715497,
  "website": "https://www.mckbelchatow.pl/kino-kultura",
  "repertuarUrl": "https://www.mckbelchatow.pl/kino-kultura/repertuar",
  "priceNormal": 18,
  "priceDiscount": 15,
  "priceMin": 15,
  "priceNote": "Ceny 15–18 zł wg agregatora; MCK nie publikuje cennika",
  "screens": null,
  "showsPerDay": 3,
  "verified": false
 },
 {
  "name": "NoveKino Merkury",
  "city": "Biała Podlaska",
  "address": "ul. Brzeska 1",
  "lat": 52.0337583,
  "lng": 23.1206178,
  "website": "https://www.novekino.pl/kina/merkury/",
  "repertuarUrl": "https://www.novekino.pl/kina/merkury/repertuar.php",
  "priceNormal": 18,
  "priceDiscount": 15,
  "priceMin": 15,
  "priceNote": "Pon–czw 15–17 zł, pt–nd 17–18 zł wg agregatora",
  "screens": null,
  "showsPerDay": null,
  "verified": false
 },
 {
  "name": "Kino Forum",
  "city": "Białystok",
  "address": "ul. Legionowa 5",
  "lat": 53.129625,
  "lng": 23.158426,
  "website": "https://bok.bialystok.pl/",
  "repertuarUrl": "https://bok.bialystok.pl/bilety-i-znizki/nowe-ceny-biletow-w-kinie-forum/",
  "priceNormal": 23,
  "priceDiscount": 20,
  "priceMin": 18,
  "priceNote": "Bilet rodzinny (min. 3 os.) 18 zł; DKF/Klasyka Kina 20 zł",
  "screens": null,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Regis",
  "city": "Bochnia",
  "address": "ul. Regis 1",
  "lat": 49.9702354,
  "lng": 20.4287498,
  "website": "https://kino.bochnia.pl/",
  "repertuarUrl": "https://kino.bochnia.pl/",
  "priceNormal": 21,
  "priceDiscount": 17,
  "priceMin": 15,
  "priceNote": "Tani poniedziałek 17 zł; grupowy 15 zł; DKF 8–14 zł",
  "screens": 2,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Forum",
  "city": "Bolesławiec",
  "address": "pl. Piłsudskiego 1c",
  "lat": 51.261902,
  "lng": 15.5695714,
  "website": "https://kino.boleslawiec.pl/",
  "repertuarUrl": "https://kino.boleslawiec.pl/repertuar/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 17,
  "priceNote": "2D 20/18 zł, 3D 25/20 zł; KDR 19/17 zł",
  "screens": null,
  "showsPerDay": null,
  "verified": true
 },
 {
  "name": "Kino Orzeł",
  "city": "Bydgoszcz",
  "address": "ul. Marcinkowskiego 12-14",
  "lat": 53.1279,
  "lng": 18.0043,
  "website": "https://www.kino-orzel.pl/",
  "repertuarUrl": "https://www.kino-orzel.pl/bilety/",
  "priceNormal": 18,
  "priceDiscount": 15,
  "priceMin": 15,
  "priceNote": "Ulgowy 15 zł także z kartami ProKultura, KDR, Kartą Seniora",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "BCKino (Bytomskie Centrum Kultury)",
  "city": "Bytom",
  "address": "pl. Karin Stanek 1",
  "lat": 50.3489,
  "lng": 18.9203,
  "website": "https://becek.pl/",
  "repertuarUrl": "https://www.becek.pl/program/category,84",
  "priceNormal": 18,
  "priceDiscount": 15,
  "priceMin": 5,
  "priceNote": "Latem kino plenerowe 5 zł; regularny cennik nieopublikowany — ceny szacunkowe. 3 sale.",
  "screens": 3,
  "showsPerDay": 3,
  "verified": false
 },
 {
  "name": "CKF Zorza",
  "city": "Chełm",
  "address": "ul. Strażacka 2",
  "lat": 51.1335457,
  "lng": 23.4697128,
  "website": "https://www.zorzachelm.pl/",
  "repertuarUrl": "https://www.zorzachelm.pl/repertuar",
  "priceNormal": 24,
  "priceDiscount": 19,
  "priceMin": 15,
  "priceNote": "Tanie poniedziałki 17 zł; senior/grupowy 17 zł; Chełmska Karta 3+ 15 zł",
  "screens": null,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "OKF Iluzja",
  "city": "Częstochowa",
  "address": "Al. Najświętszej Maryi Panny 64",
  "lat": 50.8117,
  "lng": 19.115,
  "website": "https://okf.czest.pl/",
  "repertuarUrl": "https://okf.czest.pl/ceny-biletow/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 13,
  "priceNote": "Tanie poniedziałki: wszystkie bilety 15 zł; Kino Seniora 13 zł; Karta Stałego Widza 18/16 zł.",
  "screens": 1,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Kino Światowid",
  "city": "Elbląg",
  "address": "Plac Kazimierza Jagiellończyka 1",
  "lat": 54.166884,
  "lng": 19.404734,
  "website": "https://kino.swiatowid.elblag.pl/",
  "repertuarUrl": "https://kino.swiatowid.elblag.pl/7-cennik",
  "priceNormal": 25,
  "priceDiscount": 20,
  "priceMin": 15,
  "priceNote": "Tani poniedziałek 16 zł; wt–czw 20/18 zł; wtorki grupowe 15 zł",
  "screens": 2,
  "showsPerDay": 9,
  "verified": true
 },
 {
  "name": "Kino ECK",
  "city": "Ełk",
  "address": "ul. Wojska Polskiego 47",
  "lat": 53.820793,
  "lng": 22.34615,
  "website": "https://kino.elk.pl/",
  "repertuarUrl": "https://kino.elk.pl/",
  "priceNormal": 18,
  "priceDiscount": 16,
  "priceMin": 10,
  "priceNote": "Karta seniora 10 zł; seanse specjalne 15 zł",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Kameralne Cafe",
  "city": "Gdańsk",
  "address": "ul. Lektykarska 4",
  "lat": 54.34905,
  "lng": 18.6528,
  "website": "https://www.kinokameralnecafe.pl/",
  "repertuarUrl": "https://www.kinokameralnecafe.pl/bilety/",
  "priceNormal": 25,
  "priceDiscount": null,
  "priceMin": 12,
  "priceNote": "Brak stałego ulgowego; Kino Seniora (śr/pt 12:00) i Kino Studenckie (pon.) po 12 zł",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "KinoPort",
  "city": "Gdańsk",
  "address": "ul. Strajku Dokerów 5 (CSW Łaźnia 2)",
  "lat": 54.399,
  "lng": 18.6553,
  "website": "https://www.laznia.pl/kinoport/",
  "repertuarUrl": "https://www.laznia.pl/kinoport/cykl/repertuar-filmowy-kinoportu-280/",
  "priceNormal": 15,
  "priceDiscount": 12,
  "priceMin": 10,
  "priceNote": "10 zł: czwartki, seniorzy 60+, mieszkańcy Nowego Portu, seanse rodzinne",
  "screens": 1,
  "showsPerDay": 2,
  "verified": true
 },
 {
  "name": "Gdyńskie Centrum Filmowe",
  "city": "Gdynia",
  "address": "Plac Grunwaldzki 2",
  "lat": 54.5179,
  "lng": 18.5427,
  "website": "https://gcf.org.pl/",
  "repertuarUrl": "https://gcf.org.pl/kino-studyjne/cennik/",
  "priceNormal": 25,
  "priceDiscount": 20,
  "priceMin": 17,
  "priceNote": "Tanie poniedziałki 17 zł; wtorki z Metropolitalną Kartą do Kultury 20 zł",
  "screens": 3,
  "showsPerDay": 10,
  "verified": true
 },
 {
  "name": "Kino Amok",
  "city": "Gliwice",
  "address": "ul. Dolnych Wałów 3",
  "lat": 50.2936,
  "lng": 18.6627,
  "website": "https://amok.gliwice.pl/",
  "repertuarUrl": "https://amok.gliwice.pl/repertuar/",
  "priceNormal": 25,
  "priceDiscount": 21,
  "priceMin": 20,
  "priceNote": "Tani wtorek: 20/18 zł; Gliwicka Karta Mieszkańca -2 zł; seanse seniora 16 zł. Przerwa wakacyjna do 31.07.2026.",
  "screens": 2,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Kino 60 Krzeseł",
  "city": "Gorzów Wielkopolski",
  "address": "ul. Pomorska 73",
  "lat": 52.741496,
  "lng": 15.255987,
  "website": "https://mosart.pl/kino-60-krzesel",
  "repertuarUrl": "https://mosart.pl/oferta/detail,nID,6051",
  "priceNormal": 16,
  "priceDiscount": null,
  "priceMin": 13,
  "priceNote": "Karnet 3 filmy za 39 zł; wstęp do galerii MOS w cenie",
  "screens": 1,
  "showsPerDay": 1,
  "verified": true
 },
 {
  "name": "Kino Gryf",
  "city": "Gryfino",
  "address": "ul. Szczecińska 17",
  "lat": 53.259471,
  "lng": 14.4902045,
  "website": "https://www.gdk.com.pl/kino",
  "repertuarUrl": "https://biletyna.pl/Gryfino/Kino-Gryf",
  "priceNormal": 17,
  "priceDiscount": 15,
  "priceMin": 11,
  "priceNote": "Ceny orientacyjne — GDK nie publikuje cennika",
  "screens": 1,
  "showsPerDay": 2,
  "verified": false
 },
 {
  "name": "Kino Syrena (JDK)",
  "city": "Jasło",
  "address": "ul. Kołłątaja 1",
  "lat": 49.7443057,
  "lng": 21.4729225,
  "website": "https://kino.jdkjaslo.pl/",
  "repertuarUrl": "https://kino.jdkjaslo.pl/",
  "priceNormal": 21,
  "priceDiscount": 19,
  "priceMin": 15,
  "priceNote": "Bilet szkolny 15 zł; Karta Jaślanina 17 zł; DKF Nostromo 19/17 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Lot",
  "city": "Jelenia Góra",
  "address": "ul. Pocztowa 11/12",
  "lat": 50.9020805,
  "lng": 15.7416403,
  "website": "https://kino-lot.pl/",
  "repertuarUrl": "https://kino-lot.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 16,
  "priceNote": "Tani czwartek 16 zł (2D); karta Kinoman 16 zł; KDR 14 zł",
  "screens": 2,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Centrum (CKiS)",
  "city": "Kalisz",
  "address": "ul. Łazienna 6",
  "lat": 51.7614904,
  "lng": 18.0935256,
  "website": "https://ckis.kalisz.pl/kino/",
  "repertuarUrl": "https://kck.systembiletowy.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 10,
  "priceNote": "KINOczwartek 10 zł (2D); Poniedziałkowy Klub Filmowy karnet 14 zł",
  "screens": 1,
  "showsPerDay": 2,
  "verified": true
 },
 {
  "name": "Kino Kosmos",
  "city": "Katowice",
  "address": "ul. Sokolska 66",
  "lat": 50.2681,
  "lng": 19.0189,
  "website": "https://kosmos.katowice.pl",
  "repertuarUrl": "https://kosmos.katowice.pl/repertuar/",
  "priceNormal": 25,
  "priceDiscount": 22,
  "priceMin": 18,
  "priceNote": "Tanie poniedziałki 18 zł; karta KAŚKA 17 zł; cykle klasyki 22/18 zł; seniorzy 16 zł",
  "screens": 2,
  "showsPerDay": 10,
  "verified": true
 },
 {
  "name": "Kino Światowid",
  "city": "Katowice",
  "address": "ul. 3 Maja 7",
  "lat": 50.2594,
  "lng": 19.021,
  "website": "https://swiatowid.katowice.pl",
  "repertuarUrl": "https://swiatowid.katowice.pl/repertuar/",
  "priceNormal": 25,
  "priceDiscount": 22,
  "priceMin": 18,
  "priceNote": "Tanie poniedziałki 18 zł; karta KAŚKA 14–17 zł",
  "screens": 2,
  "showsPerDay": 11,
  "verified": true
 },
 {
  "name": "Kinoteatr Rialto",
  "city": "Katowice",
  "address": "ul. św. Jana 24",
  "lat": 50.2572,
  "lng": 19.0233,
  "website": "https://rialto.katowice.pl",
  "repertuarUrl": "https://rialto.katowice.pl/cennik/",
  "priceNormal": 25,
  "priceDiscount": 22,
  "priceMin": 18,
  "priceNote": "Tanie poniedziałki 18 zł; karta KAŚKA 17 zł; Kino Seniora 16 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Fenomen",
  "city": "Kielce",
  "address": "ul. ks. Piotra Ściegiennego 2",
  "lat": 50.863251,
  "lng": 20.626998,
  "website": "https://wdkkielce.pl/index.php/kino-fenomen/",
  "repertuarUrl": "https://wdkkielce.pl/index.php/repertuar/",
  "priceNormal": 20,
  "priceDiscount": 15,
  "priceMin": 13,
  "priceNote": "Cykl Widnokrąg Dobrego Kina 13 zł; grupy szkolne 14 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Moskwa",
  "city": "Kielce",
  "address": "ul. Stanisława Staszica 5",
  "lat": 50.870699,
  "lng": 20.626598,
  "website": "https://kinomoskwa.pl/",
  "repertuarUrl": "https://kinomoskwa.pl/cennik/",
  "priceNormal": 22,
  "priceDiscount": 18,
  "priceMin": 15,
  "priceNote": "Bilet grupowy/szkolny 15 zł (min. 15 osób, pn–pt)",
  "screens": 2,
  "showsPerDay": 8,
  "verified": true
 },
 {
  "name": "Kino Scena Kultura",
  "city": "Knurów",
  "address": "ul. Niepodległości 26",
  "lat": 50.2198882,
  "lng": 18.6644442,
  "website": "https://www.kinoscenakultura.pl/",
  "repertuarUrl": "https://www.kinoscenakultura.pl/repertuar",
  "priceNormal": 18,
  "priceDiscount": 16,
  "priceMin": null,
  "priceNote": null,
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Centrum (KCK)",
  "city": "Konin",
  "address": "Plac Niepodległości 1",
  "lat": 52.2265185,
  "lng": 18.2509361,
  "website": "https://kckkonin.pl/kino-centrum/",
  "repertuarUrl": "https://kckkonin.bilety24.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": null,
  "priceNote": "Szacunek — KCK nie publikuje cennika (agregatory: 20–22 zł)",
  "screens": 1,
  "showsPerDay": 2,
  "verified": false
 },
 {
  "name": "Kino Oskard",
  "city": "Konin",
  "address": "Aleje 1 Maja 7a",
  "lat": 52.2280972,
  "lng": 18.2545545,
  "website": "https://kinooskard.ckis.konin.pl/",
  "repertuarUrl": "https://kinooskard.ckis.konin.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 10,
  "priceNote": "Tani poniedziałek i Last Minute czwartek 16 zł; Wakacyjne Kino 10 zł",
  "screens": 2,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Kino KDK",
  "city": "Kozienice",
  "address": "ul. Warszawska 29",
  "lat": 51.5884115,
  "lng": 21.5457541,
  "website": "https://www.kinokozienice.pl/",
  "repertuarUrl": "https://www.kinokozienice.pl/",
  "priceNormal": 25,
  "priceDiscount": 21,
  "priceMin": 17,
  "priceNote": "Tani poniedziałek 17 zł, tani wtorek 23/19 zł; Kino dla Seniora 15 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Agrafka",
  "city": "Kraków",
  "address": "ul. Krowoderska 8",
  "lat": 50.069,
  "lng": 19.9384,
  "website": "https://kinoagrafka.pl",
  "repertuarUrl": "https://kinoagrafka.pl/rep.php",
  "priceNormal": 29,
  "priceDiscount": 25,
  "priceMin": 22,
  "priceNote": "Poniedziałek: każdy bilet 22 zł; senior 22 zł; weekend normalny 32 zł",
  "screens": 3,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Kijów",
  "city": "Kraków",
  "address": "al. Zygmunta Krasińskiego 34",
  "lat": 50.0567,
  "lng": 19.925,
  "website": "https://kijow.pl",
  "repertuarUrl": "https://kijow.pl/cennik/",
  "priceNormal": 29,
  "priceDiscount": 25,
  "priceMin": 21,
  "priceNote": "Poniedziałek: wszystkie bilety 21 zł; senior 20 zł codziennie; mniejsze sale tańsze (23–28 zł)",
  "screens": 4,
  "showsPerDay": null,
  "verified": true
 },
 {
  "name": "Kino Kika",
  "city": "Kraków",
  "address": "ul. Ignacego Krasickiego 18",
  "lat": 50.0416,
  "lng": 19.9372,
  "website": "https://kinokika.pl",
  "repertuarUrl": "https://bilety.kinokika.pl/",
  "priceNormal": 29,
  "priceDiscount": 25,
  "priceMin": 22,
  "priceNote": "Wtorek: wszystkie bilety 22 zł; senior 22 zł; weekend normalny 32 zł",
  "screens": 4,
  "showsPerDay": null,
  "verified": true
 },
 {
  "name": "Kino Mikro",
  "city": "Kraków",
  "address": "ul. Juliusza Lea 5",
  "lat": 50.0662,
  "lng": 19.9183,
  "website": "https://kinomikro.pl",
  "repertuarUrl": "https://kinomikro.pl/",
  "priceNormal": 27,
  "priceDiscount": 26,
  "priceMin": 21,
  "priceNote": "Tani poniedziałek: wszystkie bilety 21 zł; senior 22 zł; weekend normalny 29 zł",
  "screens": 2,
  "showsPerDay": null,
  "verified": true
 },
 {
  "name": "Kino Paradox",
  "city": "Kraków",
  "address": "ul. Krupnicza 38",
  "lat": 50.0634,
  "lng": 19.9268,
  "website": "https://kinoparadox.pl",
  "repertuarUrl": "https://kinoparadox.pl/repertuar/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 14,
  "priceNote": "Sala Relax 14 zł; środy 'wszyscy jesteśmy seniorami' 15 zł; senior 15 zł",
  "screens": 2,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Pod Baranami",
  "city": "Kraków",
  "address": "Rynek Główny 27",
  "lat": 50.0611,
  "lng": 19.9349,
  "website": "https://www.kinopodbaranami.pl",
  "repertuarUrl": "https://www.kinopodbaranami.pl/repertuar.php",
  "priceNormal": 29,
  "priceDiscount": 26,
  "priceMin": 22.9,
  "priceNote": "Poniedziałek: bilety 22,90 zł; senior 23 zł; weekend normalny 31 zł",
  "screens": 3,
  "showsPerDay": 21,
  "verified": true
 },
 {
  "name": "Kino Sfinks",
  "city": "Kraków",
  "address": "os. Górali 5",
  "lat": 50.0798268,
  "lng": 20.0364042,
  "website": "https://kinosfinks.okn.edu.pl/",
  "repertuarUrl": "https://kinosfinks.okn.edu.pl/strona-3388-cennik.html",
  "priceNormal": 25,
  "priceDiscount": 20,
  "priceMin": 19,
  "priceNote": "Tani wtorek 19 zł; weekend 27/21 zł; seanse 'Mały Metraż' 21/18 zł",
  "screens": 2,
  "showsPerDay": null,
  "verified": true
 },
 {
  "name": "artKino (RCKP)",
  "city": "Krosno",
  "address": "ul. Bieszczadzka 1",
  "lat": 49.6787289,
  "lng": 21.7749453,
  "website": "https://artkino.rckp.krosno.pl/",
  "repertuarUrl": "https://bilety.rckp.krosno.pl/",
  "priceNormal": 18,
  "priceDiscount": 16,
  "priceMin": null,
  "priceNote": "Ceny z portalu krosno24.pl — brak oficjalnego cennika online",
  "screens": 1,
  "showsPerDay": 3,
  "verified": false
 },
 {
  "name": "Kino Piast",
  "city": "Legnica",
  "address": "ul. Biskupia 5",
  "lat": 51.2093655,
  "lng": 16.1662065,
  "website": "https://kino-piast.pl/",
  "repertuarUrl": "https://kino-piast.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 16,
  "priceNote": "Tania środa 2D 16 zł; 3D 25/22 zł; edukacja filmowa 12 zł",
  "screens": null,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Bajka",
  "city": "Lublin",
  "address": "ul. Idziego Radziszewskiego 8",
  "lat": 51.246424,
  "lng": 22.543769,
  "website": "https://kinobajka.pl/",
  "repertuarUrl": "https://kinobajka.pl/repertuar/",
  "priceNormal": 26,
  "priceDiscount": 23,
  "priceMin": 19,
  "priceNote": "Tani poniedziałek — każdy seans 19 zł",
  "screens": 2,
  "showsPerDay": 9,
  "verified": true
 },
 {
  "name": "Kino w Chatce Żaka (ACKiM UMCS)",
  "city": "Lublin",
  "address": "ul. Idziego Radziszewskiego 16",
  "lat": 51.245101,
  "lng": 22.537843,
  "website": "https://www.chatkazaka.pl/",
  "repertuarUrl": "https://www.ebilet.pl/miejsce/ack-umcs-chatka-zaka",
  "priceNormal": 22.9,
  "priceDiscount": null,
  "priceMin": null,
  "priceNote": "Bilety per wydarzenie przez eBilet",
  "screens": 1,
  "showsPerDay": 1,
  "verified": false
 },
 {
  "name": "Kino Galaktyka",
  "city": "Mielec",
  "address": "al. Niepodległości 7",
  "lat": 50.2953828,
  "lng": 21.4394881,
  "website": "https://kinogalaktyka.pl/",
  "repertuarUrl": "https://bilety.kinogalaktyka.pl/",
  "priceNormal": 17,
  "priceDiscount": 15,
  "priceMin": 13,
  "priceNote": "Pt–nd 17/15 zł; wt–czw 15/13 zł; tani poniedziałek 13 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Sokół (MCK SOKÓŁ)",
  "city": "Nowy Sącz",
  "address": "ul. Długosza 3",
  "lat": 49.6223134,
  "lng": 20.6947968,
  "website": "https://www.kino-sokol.pl/",
  "repertuarUrl": "https://www.kino-sokol.pl/repertuar-kina-6.html",
  "priceNormal": 19,
  "priceDiscount": 16,
  "priceMin": 10,
  "priceNote": "2D 19/16 zł, 3D 23/19 zł; KDR 15 zł; cykle filmowe 10–19 zł",
  "screens": 3,
  "showsPerDay": 8,
  "verified": true
 },
 {
  "name": "Kino Awangarda 2",
  "city": "Olsztyn",
  "address": "Plac Jana Pawła II 2/3",
  "lat": 53.777985,
  "lng": 20.479376,
  "website": "https://www.awangarda.olsztyn.pl/",
  "repertuarUrl": "https://www.awangarda.olsztyn.pl/",
  "priceNormal": 30,
  "priceDiscount": 26,
  "priceMin": 24,
  "priceNote": "Wt–czw taniej: 28/24 zł; edukacja filmowa 20 zł",
  "screens": 3,
  "showsPerDay": 6,
  "verified": true
 },
 {
  "name": "Kino Meduza",
  "city": "Opole",
  "address": "ul. Oleska 45",
  "lat": 50.674141,
  "lng": 17.931577,
  "website": "https://kinomeduza.pl/",
  "repertuarUrl": "https://kinomeduza.pl/bilety/",
  "priceNormal": 25,
  "priceDiscount": 20,
  "priceMin": null,
  "priceNote": null,
  "screens": 3,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Studio (MDK)",
  "city": "Opole",
  "address": "ul. Strzelców Bytomskich 1",
  "lat": 50.665377,
  "lng": 17.921652,
  "website": "https://mdk.opole.pl/",
  "repertuarUrl": "https://mdk.opole.pl/kino-studio.html",
  "priceNormal": 15,
  "priceDiscount": null,
  "priceMin": 10,
  "priceNote": "Wybrane seanse za 10 zł",
  "screens": 1,
  "showsPerDay": 1,
  "verified": true
 },
 {
  "name": "Kino Jantar",
  "city": "Ostrołęka",
  "address": "ul. Inwalidów Wojennych 23",
  "lat": 53.079615,
  "lng": 21.576203,
  "website": "https://ock-ostroleka.pl/osrodki/kino-jantar/",
  "repertuarUrl": "https://ock-ostroleka.pl/osrodki/kino-jantar/cennik-biletow/",
  "priceNormal": 26,
  "priceDiscount": 24,
  "priceMin": 20,
  "priceNote": "Tanie wtorki 20 zł; pn–czw taniej (24/22 zł)",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Charlie Monroe Kino Malta",
  "city": "Poznań",
  "address": "ul. Rybaki 6a",
  "lat": 52.39876,
  "lng": 16.93188,
  "website": "https://www.kinomalta.pl/",
  "repertuarUrl": "https://kinomalta.pl/nasze-kino/cennik.html",
  "priceNormal": 26,
  "priceDiscount": 24,
  "priceMin": 19,
  "priceNote": "Tani poniedziałek 21 zł; bajki dla dzieci 19 zł",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Apollo",
  "city": "Poznań",
  "address": "ul. Ratajczaka 18",
  "lat": 52.4051,
  "lng": 16.9219,
  "website": "https://kinoapollo.pl/",
  "repertuarUrl": "https://kinoapollo.pl/repertuar/",
  "priceNormal": null,
  "priceDiscount": null,
  "priceMin": null,
  "priceNote": "Cennik niepublikowany na stronie; ceny w systemie bilety.kinoapollo.pl",
  "screens": 2,
  "showsPerDay": 3,
  "verified": false
 },
 {
  "name": "Kino Bułgarska 19",
  "city": "Poznań",
  "address": "ul. Bułgarska 19 (Stadion Poznań)",
  "lat": 52.3975,
  "lng": 16.8586,
  "website": "https://kinobulgarska19.pl/",
  "repertuarUrl": "https://kinobulgarska19.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 18,
  "priceNote": "Kameralna sala na 50 miejsc; ceny wg agregatorów repertuaru",
  "screens": 1,
  "showsPerDay": 2,
  "verified": false
 },
 {
  "name": "Kino Muza",
  "city": "Poznań",
  "address": "ul. Św. Marcin 30",
  "lat": 52.40775,
  "lng": 16.92665,
  "website": "https://www.kinomuza.pl/",
  "repertuarUrl": "https://www.kinomuza.pl/repertuar/",
  "priceNormal": 20,
  "priceDiscount": 17,
  "priceMin": 14,
  "priceNote": "14 zł: seniorzy z kartą, grupy, program OK Poznań",
  "screens": 2,
  "showsPerDay": 8,
  "verified": true
 },
 {
  "name": "Kino Pałacowe",
  "city": "Poznań",
  "address": "ul. Św. Marcin 80/82 (CK Zamek)",
  "lat": 52.4085,
  "lng": 16.9185,
  "website": "https://kinopalacowe.pl/",
  "repertuarUrl": "https://kinopalacowe.pl/podstrony/371-repertuar/",
  "priceNormal": 25,
  "priceDiscount": 23,
  "priceMin": 16,
  "priceNote": "16 zł z Kartą Kinomana na seanse plenerowe; Kino bez barier 5 zł",
  "screens": 2,
  "showsPerDay": 6,
  "verified": true
 },
 {
  "name": "Kino Rialto",
  "city": "Poznań",
  "address": "ul. Dąbrowskiego 38",
  "lat": 52.41481,
  "lng": 16.90724,
  "website": "https://www.kinorialto.poznan.pl/",
  "repertuarUrl": "https://www.kinorialto.poznan.pl/cennik",
  "priceNormal": 24,
  "priceDiscount": 20,
  "priceMin": 17,
  "priceNote": "Tani czwartek 17 zł; klub filmowy 15 zł",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino na Bursztynowym Szlaku",
  "city": "Pruszcz Gdański",
  "address": "ul. Chopina 34",
  "lat": 54.2586,
  "lng": 18.6304,
  "website": "https://ckis-pruszcz.pl/",
  "repertuarUrl": "http://kino.ckis-pruszcz.pl/",
  "priceNormal": 20,
  "priceDiscount": 17,
  "priceMin": 15,
  "priceNote": "Z Pruszczańską Kartą Mieszkańca: 18/15 zł; grupowy 16 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Centrum",
  "city": "Przemyśl",
  "address": "ul. Konarskiego 9",
  "lat": 49.7852,
  "lng": 22.7629,
  "website": "https://www.ck.przemysl.pl/kino-centrum/nasze-kino",
  "repertuarUrl": "https://www.ck.przemysl.pl/kino-centrum/repertuar",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 15,
  "priceNote": "DKF Filmiarnia 15 zł; 3D 25/20 zł",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "NoveKino Sybilla",
  "city": "Puławy",
  "address": "al. Partyzantów 6",
  "lat": 51.4152,
  "lng": 21.969,
  "website": "https://www.novekino.pl/kina/sybilla/",
  "repertuarUrl": "https://www.novekino.pl/kina/sybilla/repertuar.php",
  "priceNormal": 19,
  "priceDiscount": 17,
  "priceMin": 14,
  "priceNote": "Tanie poniedziałki 14 zł; wt–czw 17/15 zł; pt–nd 16–19 zł",
  "screens": null,
  "showsPerDay": 5,
  "verified": false
 },
 {
  "name": "NoveKino Przedwiośnie",
  "city": "Płock",
  "address": "ul. Tumska 5a",
  "lat": 52.5437275,
  "lng": 19.6894116,
  "website": "https://www.novekino.pl/kina/przedwiosnie/",
  "repertuarUrl": "https://www.novekino.pl/kina/przedwiosnie/",
  "priceNormal": 31,
  "priceDiscount": 27,
  "priceMin": 17,
  "priceNote": "2D pt–nd 31/27 zł, pon–czw 27/24 zł; grupowe 19 zł, edukacyjne 17 zł",
  "screens": 3,
  "showsPerDay": 13,
  "verified": true
 },
 {
  "name": "Kino Bałtyk",
  "city": "Racibórz",
  "address": "ul. Londzina 13",
  "lat": 50.0936,
  "lng": 18.2224,
  "website": "https://kinobaltyk.pl/",
  "repertuarUrl": "https://kinobaltyk.pl/repertuar/",
  "priceNormal": 25,
  "priceDiscount": 22,
  "priceMin": 18,
  "priceNote": "Tani poniedziałek: wszystkie bilety 2D 18 zł; zbiorowy 17 zł",
  "screens": null,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino MCSW Elektrownia",
  "city": "Radom",
  "address": "ul. Mikołaja Kopernika 1",
  "lat": 51.4062,
  "lng": 21.1571,
  "website": "https://www.mcswelektrownia.pl/",
  "repertuarUrl": "https://www.mcswelektrownia.pl/pl/kino",
  "priceNormal": 23,
  "priceDiscount": null,
  "priceMin": 15,
  "priceNote": "Tani poniedziałek 15 zł; wt–czw 19 zł; pt–nd 23 zł; dzieci 17 zł",
  "screens": null,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Pasja",
  "city": "Radomsko",
  "address": "ul. Brzeźnicka 5",
  "lat": 51.066,
  "lng": 19.4405,
  "website": "https://mdkradomsko.pl/kino/",
  "repertuarUrl": "https://mdkradomsko.bilety24.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 15,
  "priceNote": "Tani poniedziałek 15 zł; 'W samo południe' i poranki 16 zł",
  "screens": 1,
  "showsPerDay": 2,
  "verified": true
 },
 {
  "name": "Kino Zorza",
  "city": "Rzeszów",
  "address": "ul. 3 Maja 28",
  "lat": 50.03493,
  "lng": 22.000554,
  "website": "https://www.kinozorza.pl/",
  "repertuarUrl": "https://kinozorza.pl/cennik",
  "priceNormal": 24,
  "priceDiscount": 22,
  "priceMin": 17,
  "priceNote": "Tani poniedziałek i czwartek — bilety 17 zł; wt–śr taniej (22/20 zł)",
  "screens": 3,
  "showsPerDay": 15,
  "verified": true
 },
 {
  "name": "Kino Starówka",
  "city": "Sandomierz",
  "address": "Rynek 25/26",
  "lat": 50.6795,
  "lng": 21.749,
  "website": "https://www.kinostarowka.com.pl/",
  "repertuarUrl": "https://www.kinostarowka.com.pl/repertuar",
  "priceNormal": 18,
  "priceDiscount": 16,
  "priceMin": 12,
  "priceNote": "Środa dla seniora 12 zł; KDR i Karta Seniora -20%; 3D 22/20 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "NoveKino Siedlce",
  "city": "Siedlce",
  "address": "ul. Wiszniewskiego 4",
  "lat": 52.1665,
  "lng": 22.285,
  "website": "https://www.novekino.pl/kina/siedlce/",
  "repertuarUrl": "https://www.novekino.pl/kina/siedlce/rezerwacja.php",
  "priceNormal": 26,
  "priceDiscount": 22,
  "priceMin": 20,
  "priceNote": "Pn–czw taniej (ok. 24/20 zł); tani poniedziałek; ceny wg agregatora",
  "screens": null,
  "showsPerDay": 15,
  "verified": false
 },
 {
  "name": "Kinoteatr Polonez",
  "city": "Skierniewice",
  "address": "ul. Wita Stwosza 2/4",
  "lat": 51.9545,
  "lng": 20.143,
  "website": "https://kino.cekis.pl/",
  "repertuarUrl": "https://kino.cekis.pl/repertuar/",
  "priceNormal": 28,
  "priceDiscount": 22,
  "priceMin": 20,
  "priceNote": "Tani wtorek 20 zł; grupy szkolne 16 zł; 3D 30/24 zł",
  "screens": 2,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Mazowsze",
  "city": "Sochaczew",
  "address": "ul. Fryderyka Chopina 101",
  "lat": 52.256,
  "lng": 20.233,
  "website": "https://e-sochaczew.pl/kinomazowsze",
  "repertuarUrl": "https://e-sochaczew.pl/kinomazowsze/repertuar",
  "priceNormal": 22,
  "priceDiscount": 18,
  "priceMin": null,
  "priceNote": "Ceny wg agregatorów; 1 sala ok. 270 miejsc, Mazowiecka Sieć Kin",
  "screens": 1,
  "showsPerDay": 2,
  "verified": false
 },
 {
  "name": "Kino Odeon",
  "city": "Sochaczew",
  "address": "ul. Stefana Żeromskiego 8",
  "lat": 52.229,
  "lng": 20.24,
  "website": "https://kinoodeon.pl/",
  "repertuarUrl": "https://kinoodeon.pl/repertuar/",
  "priceNormal": 28,
  "priceDiscount": 26,
  "priceMin": 21,
  "priceNote": "Pn–pt do 17:00: 28/26 zł; weekend 31/29 zł; tani poniedziałek 21 zł; senior 23–25 zł",
  "screens": null,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Cinema Lumiere",
  "city": "Suwałki",
  "address": "ul. Dwernickiego 15 (Suwałki Plaza)",
  "lat": 54.107529,
  "lng": 22.933515,
  "website": "https://cinema-lumiere.pl/suwalki/",
  "repertuarUrl": "https://cinema-lumiere.pl/suwalki/cennik-biletow/",
  "priceNormal": 28,
  "priceDiscount": 24,
  "priceMin": 20,
  "priceNote": "Pn–pt przed 15:00 wszystkie bilety 20 zł; Kino Konesera 25 zł",
  "screens": 4,
  "showsPerDay": 6,
  "verified": true
 },
 {
  "name": "Kino Pionier 1907",
  "city": "Szczecin",
  "address": "al. Wojska Polskiego 2",
  "lat": 53.428,
  "lng": 14.5489,
  "website": "https://pionier1907.pl/",
  "repertuarUrl": "https://pionier1907.pl/cennik/",
  "priceNormal": 25,
  "priceDiscount": 22,
  "priceMin": 18,
  "priceNote": "Tani poniedziałek 18 zł; środy 13:00 za 18 zł",
  "screens": 2,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Kino Górnik",
  "city": "Szydłowiec",
  "address": "ul. Strażacka 1",
  "lat": 51.2244,
  "lng": 20.8613,
  "website": "https://kinoszydlowiec.pl/",
  "repertuarUrl": "https://kinoszydlowiec.pl/",
  "priceNormal": 21,
  "priceDiscount": 18,
  "priceMin": 17,
  "priceNote": "Wt–czw 21/18 zł; weekend 23–25/20–22 zł; Kinokarta 17 zł",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "Kino Rejs",
  "city": "Słupsk",
  "address": "al. 3 Maja 22",
  "lat": 54.474122,
  "lng": 17.00802,
  "website": "https://www.sok.slupsk.pl/",
  "repertuarUrl": "https://www.sok.slupsk.pl/index.php/kino-rejs/repertuar-kina-rejs",
  "priceNormal": 22,
  "priceDiscount": 18,
  "priceMin": 14,
  "priceNote": "Wtorek seniora 16 zł; DKF i cykl WAJDA 14 zł; Karta Mieszkańca -2 zł",
  "screens": 1,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Wisła",
  "city": "Tarnobrzeg",
  "address": "ul. Słowackiego 2",
  "lat": 50.573,
  "lng": 21.678,
  "website": "https://kino.tdk.tarnobrzeg.pl/",
  "repertuarUrl": "https://kino.tdk.tarnobrzeg.pl/repertuar/",
  "priceNormal": null,
  "priceDiscount": null,
  "priceMin": null,
  "priceNote": "Cennik niepublikowany online; bilety przez tdk.biletpro24.pl",
  "screens": null,
  "showsPerDay": null,
  "verified": false
 },
 {
  "name": "Kino Marzenie",
  "city": "Tarnów",
  "address": "ul. Staszica 4",
  "lat": 50.0146,
  "lng": 20.9857,
  "website": "https://www.kinomarzenie.pl/",
  "repertuarUrl": "https://www.kinomarzenie.pl/repertuar",
  "priceNormal": 22,
  "priceDiscount": 20,
  "priceMin": 15,
  "priceNote": "Seanse zorganizowane 15 zł; ulgowy do 26 r.ż., KDR, seniorzy",
  "screens": null,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Kino Millennium",
  "city": "Tarnów",
  "address": "ul. Traugutta 1",
  "lat": 50.009,
  "lng": 20.925,
  "website": "https://kino.tarnow.pl/",
  "repertuarUrl": "https://kino.tarnow.pl/wydarzenia/repertuar",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 15,
  "priceNote": "Sala kameralna 17/15 zł; cykle 15 zł; Babskie Poniedziałki 16 zł",
  "screens": 2,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino CAMERIMAGE",
  "city": "Toruń",
  "address": "Rynek Nowomiejski 28",
  "lat": 53.0114,
  "lng": 18.6113,
  "website": "https://kinocamerimage.pl/",
  "repertuarUrl": "https://kinocamerimage.pl/",
  "priceNormal": 16,
  "priceDiscount": 12,
  "priceMin": 12,
  "priceNote": "Kino tymczasowo nieczynne (stan 07.2026); ceny z ostatniego cennika",
  "screens": 1,
  "showsPerDay": 0,
  "verified": false
 },
 {
  "name": "Kino Centrum WCK",
  "city": "Wadowice",
  "address": "ul. Teatralna 1",
  "lat": 49.8837,
  "lng": 19.4899,
  "website": "https://wck.wadowice.pl/kino/",
  "repertuarUrl": "https://wck.wadowice.pl/kino/",
  "priceNormal": 19,
  "priceDiscount": 16,
  "priceMin": 14,
  "priceNote": "Grupowy/KDR 14 zł; cykl środAwisko 14 zł; okulary 3D +4 zł",
  "screens": null,
  "showsPerDay": 3,
  "verified": false
 },
 {
  "name": "Kino Amondo",
  "city": "Warszawa",
  "address": "ul. Żurawia 20",
  "lat": 52.2286,
  "lng": 21.0156,
  "website": "https://kinoamondo.pl",
  "repertuarUrl": "https://kinoamondo.pl/repertuar/",
  "priceNormal": 21,
  "priceDiscount": 16,
  "priceMin": 16,
  "priceNote": "Tanie wtorki: bilet zwykły 16 zł; weekend drożej (26/21 zł)",
  "screens": 2,
  "showsPerDay": 6,
  "verified": true
 },
 {
  "name": "Kino Atlantic",
  "city": "Warszawa",
  "address": "ul. Chmielna 33",
  "lat": 52.2312,
  "lng": 21.0134,
  "website": "https://www.novekino.pl/kina/atlantic",
  "repertuarUrl": "https://www.novekino.pl/kina/atlantic/cennik.php",
  "priceNormal": 19,
  "priceDiscount": 14,
  "priceMin": 14,
  "priceNote": "Tani poniedziałek i tania środa — ceny ulgowe dla wszystkich; Pora dla Seniora 15 zł (60+)",
  "screens": 4,
  "showsPerDay": 17,
  "verified": true
 },
 {
  "name": "Kino Elektronik",
  "city": "Warszawa",
  "address": "ul. gen. Zajączka 7",
  "lat": 52.2633,
  "lng": 20.9893,
  "website": "https://kinoelektronik.pl",
  "repertuarUrl": "https://kinoelektronik.pl/",
  "priceNormal": 18,
  "priceDiscount": 15,
  "priceMin": 15,
  "priceNote": "Duża sala pon–czw 18/15 zł, pt–nd 20/16 zł; mała sala 15–16 zł (dane z agregatora)",
  "screens": 2,
  "showsPerDay": 4,
  "verified": false
 },
 {
  "name": "Kino Iluzjon",
  "city": "Warszawa",
  "address": "ul. Narbutta 50a",
  "lat": 52.2096,
  "lng": 21.0181,
  "website": "https://www.iluzjon.fn.org.pl",
  "repertuarUrl": "https://www.iluzjon.fn.org.pl/static/9/26/bilety.html",
  "priceNormal": 25,
  "priceDiscount": 20,
  "priceMin": 15,
  "priceNote": "Filmy z kolekcji FINA taniej: 18 zł normalny / 15 zł ulgowy",
  "screens": 2,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Kultura",
  "city": "Warszawa",
  "address": "Krakowskie Przedmieście 21/23",
  "lat": 52.2427,
  "lng": 21.0156,
  "website": "https://www.kinokultura.pl",
  "repertuarUrl": "https://www.kinokultura.pl/",
  "priceNormal": 17,
  "priceDiscount": 14,
  "priceMin": 12,
  "priceNote": "Poniedziałki 12 zł; ceny z serwisów zewnętrznych, oficjalna strona nie publikuje cennika",
  "screens": 2,
  "showsPerDay": 5,
  "verified": false
 },
 {
  "name": "Kino Luna",
  "city": "Warszawa",
  "address": "ul. Marszałkowska 28",
  "lat": 52.2216,
  "lng": 21.0174,
  "website": "https://kinoluna.pl",
  "repertuarUrl": "https://kinoluna.pl/repertuar/",
  "priceNormal": 25,
  "priceDiscount": 21,
  "priceMin": 12,
  "priceNote": "Tani poniedziałek 10–12 zł (wybrane tytuły), tani czwartek 15 zł",
  "screens": 2,
  "showsPerDay": 6,
  "verified": false
 },
 {
  "name": "Kino Muranów",
  "city": "Warszawa",
  "address": "ul. gen. Andersa 5",
  "lat": 52.247,
  "lng": 20.9986,
  "website": "https://kinomuranow.pl",
  "repertuarUrl": "https://kinomuranow.pl/bilety",
  "priceNormal": 28,
  "priceDiscount": 23,
  "priceMin": 20,
  "priceNote": "Poniedziałek: wszystkie bilety 20 zł; weekend 30/28 zł",
  "screens": 4,
  "showsPerDay": 13,
  "verified": true
 },
 {
  "name": "Kino U-jazdowski",
  "city": "Warszawa",
  "address": "ul. Jazdów 2",
  "lat": 52.2242,
  "lng": 21.0287,
  "website": "https://u-jazdowski.pl",
  "repertuarUrl": "https://u-jazdowski.pl/program/kino",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 16,
  "priceNote": "Poniedziałek: 16/14 zł; z Kartą Widza od 12 zł; weekend 22/20 zł",
  "screens": 1,
  "showsPerDay": 2,
  "verified": true
 },
 {
  "name": "Kino Wisła",
  "city": "Warszawa",
  "address": "pl. Wilsona 2",
  "lat": 52.269,
  "lng": 20.9843,
  "website": "https://www.novekino.pl/kina/wisla/",
  "repertuarUrl": "https://www.novekino.pl/kina/wisla/cennik.php",
  "priceNormal": 26,
  "priceDiscount": 23,
  "priceMin": 18,
  "priceNote": "Tani poniedziałek 18 zł, tania środa 20 zł; senior wt–czw 17 zł; weekend 30/26 zł",
  "screens": 3,
  "showsPerDay": 8,
  "verified": true
 },
 {
  "name": "Kinokawiarnia Stacja Falenica",
  "city": "Warszawa",
  "address": "ul. Patriotów 44B",
  "lat": 52.161,
  "lng": 21.2132,
  "website": "https://stacjafalenica.pl",
  "repertuarUrl": "https://ksf.systembiletowy.pl/",
  "priceNormal": 23,
  "priceDiscount": 20,
  "priceMin": 17,
  "priceNote": "Tani poniedziałek 17 zł na wszystko; weekend 26/23 zł",
  "screens": 2,
  "showsPerDay": 7,
  "verified": true
 },
 {
  "name": "Kinoteka",
  "city": "Warszawa",
  "address": "pl. Defilad 1 (PKiN)",
  "lat": 52.2317,
  "lng": 21.0055,
  "website": "https://kinoteka.pl",
  "repertuarUrl": "https://kinoteka.pl/cennik/",
  "priceNormal": 26,
  "priceDiscount": 24,
  "priceMin": 15,
  "priceNote": "Filmowy poniedziałek 18 zł, środa 19 zł, Film dnia 15 zł (pn–pt)",
  "screens": 8,
  "showsPerDay": 20,
  "verified": true
 },
 {
  "name": "Kino Apollo",
  "city": "Wałbrzych",
  "address": "al. Armii Krajowej 42",
  "lat": 50.7857,
  "lng": 16.2873,
  "website": "https://www.kino-apollo.pl/",
  "repertuarUrl": "https://kino-apollo.bilety24.pl/",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 16,
  "priceNote": "Tani wtorek 2D 16 zł; Karta Kinomana 16 zł; 3D 25/22 zł; KDR 14 zł",
  "screens": null,
  "showsPerDay": 4,
  "verified": true
 },
 {
  "name": "Kino Morze WCK",
  "city": "Wejherowo",
  "address": "ul. Jana III Sobieskiego 255",
  "lat": 54.6027,
  "lng": 18.2277,
  "website": "https://wck.org.pl/kino-morze/",
  "repertuarUrl": "https://wck.org.pl/category/wydarzenia/kino/",
  "priceNormal": 19,
  "priceDiscount": 17,
  "priceMin": 15,
  "priceNote": "Bilet grupowy 15 zł (od 10 osób)",
  "screens": 1,
  "showsPerDay": 2,
  "verified": true
 },
 {
  "name": "Dolnośląskie Centrum Filmowe",
  "city": "Wrocław",
  "address": "ul. Piłsudskiego 64a",
  "lat": 51.10165,
  "lng": 17.02523,
  "website": "https://www.dcf.wroclaw.pl/",
  "repertuarUrl": "https://www.dcf.wroclaw.pl/ceny-biletow/",
  "priceNormal": 21,
  "priceDiscount": 18,
  "priceMin": 16,
  "priceNote": "Tania środa 16 zł, studenckie czwartki 16 zł; weekend 25/21 zł",
  "screens": 4,
  "showsPerDay": 18,
  "verified": true
 },
 {
  "name": "Kino Nowe Horyzonty",
  "city": "Wrocław",
  "address": "ul. Kazimierza Wielkiego 19a-21",
  "lat": 51.10855,
  "lng": 17.0276,
  "website": "https://www.kinonh.pl/",
  "repertuarUrl": "https://www.kinonh.pl/program.s",
  "priceNormal": 22,
  "priceDiscount": 19,
  "priceMin": 17,
  "priceNote": "19 zł z Kartą Przyjaciela KNH/Urbancard Premium; pakiety 5+ za 18 zł, 10+ za 17 zł",
  "screens": 9,
  "showsPerDay": 35,
  "verified": true
 },
 {
  "name": "Kino MDK",
  "city": "Wągrowiec",
  "address": "ul. Kościuszki 55",
  "lat": 52.8186,
  "lng": 17.203,
  "website": "https://mdkwagrowiec.pl/kino/",
  "repertuarUrl": "https://mdkwagrowiec.pl/repertuar/",
  "priceNormal": 24,
  "priceDiscount": 22,
  "priceMin": 20,
  "priceNote": "Dzieci do 6 lat i grupowy 20 zł; rodzinny 66 zł; zniżki KDR/senior",
  "screens": 1,
  "showsPerDay": 3,
  "verified": true
 },
 {
  "name": "CKF Stylowy",
  "city": "Zamość",
  "address": "ul. Odrodzenia 9",
  "lat": 50.7142,
  "lng": 23.2689,
  "website": "https://www.stylowy.net/",
  "repertuarUrl": "https://www.stylowy.net/repertuar/",
  "priceNormal": 25,
  "priceDiscount": 22,
  "priceMin": 20,
  "priceNote": "Tani wtorek 20 zł; weekend 28/24 zł; sala studyjna 15/12 zł",
  "screens": 3,
  "showsPerDay": 8,
  "verified": true
 },
 {
  "name": "Kino Newa",
  "city": "Zielona Góra",
  "address": "ul. Kazimierza Wielkiego 21",
  "lat": 51.944454,
  "lng": 15.513277,
  "website": "https://www.facebook.com/kkfnewa/",
  "repertuarUrl": "https://www.filmweb.pl/showtimes/Zielona+G%C3%B3ra/Newa-126",
  "priceNormal": 14,
  "priceDiscount": 12,
  "priceMin": null,
  "priceNote": "Brak własnej strony; ceny wg agregatorów",
  "screens": 1,
  "showsPerDay": null,
  "verified": false
 },
 {
  "name": "Kino Millenium",
  "city": "Łomża",
  "address": "ul. Wojska Polskiego 7",
  "lat": 53.17996,
  "lng": 22.072541,
  "website": "https://kinomillenium.pl/",
  "repertuarUrl": "https://kinomillenium.pl/cennik/",
  "priceNormal": 25,
  "priceDiscount": 21,
  "priceMin": 19,
  "priceNote": "Pn–czw taniej: 23/19 zł (ceny wg agregatorów)",
  "screens": 3,
  "showsPerDay": 6,
  "verified": false
 },
 {
  "name": "Kino Fenix (ŁOK)",
  "city": "Łowicz",
  "address": "ul. Podrzeczna 20",
  "lat": 52.1083022,
  "lng": 19.9391175,
  "website": "https://lok.art.pl/kino-fenix/",
  "repertuarUrl": "https://lok.art.pl/repertuar-kina-fenix/",
  "priceNormal": 18,
  "priceDiscount": 16,
  "priceMin": 12,
  "priceNote": "2D 18/16 zł, dzieci 14 zł, grupy 12 zł; 3D 20/18 zł (wg lowicz24.eu)",
  "screens": 1,
  "showsPerDay": 3,
  "verified": false
 },
 {
  "name": "Kino Charlie",
  "city": "Łódź",
  "address": "ul. Piotrkowska 203/205",
  "lat": 51.7549718,
  "lng": 19.4586413,
  "website": "https://www.charlie.pl/",
  "repertuarUrl": "https://www.charlie.pl/index.php?i=repertuargodzinowy",
  "priceNormal": 23,
  "priceDiscount": 21,
  "priceMin": 19,
  "priceNote": "Poniedziałek 19 zł; środa/niedziela seniora i studencki czwartek 19 zł; przy kasie tuż przed seansem drożej (do 29,99 zł); weekend 25/21 zł",
  "screens": 8,
  "showsPerDay": 25,
  "verified": true
 },
 {
  "name": "Kino Kinematograf",
  "city": "Łódź",
  "address": "pl. Zwycięstwa 1",
  "lat": 51.7596098,
  "lng": 19.4746179,
  "website": "https://muzeumkinematografii.pl/",
  "repertuarUrl": "https://muzeumkinematografii.pl/kino/repertuar-kina/",
  "priceNormal": 19,
  "priceDiscount": 17,
  "priceMin": 10,
  "priceNote": "Z biletem do muzeum (do 30 dni) seans za 10 zł; Mały Kinematograf 15 zł; pon-wt kino nieczynne",
  "screens": 1,
  "showsPerDay": 2,
  "verified": true
 },
 {
  "name": "Kino Wrzos",
  "city": "Świecie",
  "address": "ul. Wojska Polskiego 139",
  "lat": 53.4095,
  "lng": 18.4467,
  "website": "https://ckswiecie.eu/kino-wrzos",
  "repertuarUrl": "https://ckswiecie.eu/kino-wrzos/repertuar",
  "priceNormal": 20,
  "priceDiscount": 18,
  "priceMin": 16,
  "priceNote": "Tani wtorek 16 zł (2D i 3D); weekend 21/19 zł; Senior w Kinie 12 zł",
  "screens": null,
  "showsPerDay": 5,
  "verified": true
 },
 {
  "name": "Kino Len",
  "city": "Żyrardów",
  "address": "pl. Jana Pawła II 3",
  "lat": 52.057,
  "lng": 20.4386,
  "website": "https://kinolen.pl/",
  "repertuarUrl": "https://kinolen.pl/",
  "priceNormal": 25,
  "priceDiscount": 20,
  "priceMin": null,
  "priceNote": "Cennik od 2022 (wg agregatora); ulgowy: uczniowie, studenci, emeryci",
  "screens": 1,
  "showsPerDay": 3,
  "verified": false
 }
];
const KINA_UPDATED = "2026-07-29";
